/*!40101 SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;
/*!40101 SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table shipping_rate.txn_shipping_rate_detail
DROP TABLE IF EXISTS `txn_shipping_rate_detail`;
CREATE TABLE IF NOT EXISTS `txn_shipping_rate_detail`
(
    `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
    `logisticComp` VARCHAR(5) NULL DEFAULT NULL COMMENT '"jnt" or "city"',
    `senderPostcode` VARCHAR(5) NULL DEFAULT NULL,
    `receiverPostcode` VARCHAR(5) NULL DEFAULT NULL,
    `destinationCountry` VARCHAR(50) NULL DEFAULT NULL,
    `weight` VARCHAR(50) NULL DEFAULT NULL,
    `width` VARCHAR(50) NULL DEFAULT NULL,
    `height` VARCHAR(50) NULL DEFAULT NULL,
    `length` VARCHAR(50) NULL DEFAULT NULL,
    `totalRate` VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- Data exporting was unselected.

/*!40101 SET SQL_MODE = IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS = IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT */;
